Citizen.CreateThread(function()
    -- Enable the island's scenario groups, making the island's entities (like vegetation) spawn.
    SetScenarioGroupEnabled('Heist_Island_Peds', true)

    -- Requesting IPLs for Cayo Perico to ensure all aspects of the island are loaded properly.
    RequestIpl("h4_islandairstrip")
    RequestIpl("h4_islandx_mansion")
    RequestIpl("h4_islandx_maindock")
    RequestIpl("h4_islandxdock_water_hatch")
    RequestIpl("h4_islandx_maindock_props")
    RequestIpl("h4_islandx_maindock_sealights")
    RequestIpl("h4_islandx_props")
    RequestIpl("h4_int_placement_h4")
    RequestIpl("h4_islandx_mansion_vault")
    RequestIpl("h4_islandairstrip_props")
    RequestIpl("h4_islandx_mansion_props")
    RequestIpl("h4_islandx_mansion_b")
    RequestIpl("h4_islandx_mansion_lod")
    RequestIpl("h4_islandx_mansion_guardfence")
    RequestIpl("h4_islandx_mansion_b_side_fence")
    RequestIpl("h4_islandx_mansion_lights")
    RequestIpl("h4_islandx_mansion_gate")
    RequestIpl("h4_islandx_maindock_lod")
    RequestIpl("h4_islandxdock_props")
    RequestIpl("h4_beach")
    RequestIpl("h4_beach_lod")
    RequestIpl("h4_beach_props")
    RequestIpl("h4_islandx_barrack_props")
    RequestIpl("h4_islandx_checkpoint")
    RequestIpl("h4_islandx_checkpoint_props")
    RequestIpl("h4_islandx_tower")
    RequestIpl("h4_islandx_tower_props")
    RequestIpl("h4_islandx_maindock_props_lod")
    RequestIpl("h4_islandxdock_props_lod")
    RequestIpl("h4_islandxdock_props_slod")
    RequestIpl("h4_islandx_props_lod")
    RequestIpl("h4_islandx_props_slod")
    RequestIpl("h4_islandx_mansion_office")
    RequestIpl("h4_islandx_maindock")
    RequestIpl("h4_islandx_maindock_props_2")
    RequestIpl("h4_IslandX_Mansion_B_Side_Fence_2")
    RequestIpl("h4_islandairstrip_doorsclosed")
    RequestIpl("h4_Underwater_Gate_Closed")
    RequestIpl("h4_mansion_gate_closed")
    RequestIpl("h4_aa_guns")
    RequestIpl("h4_IslandX_Mansion_GuardFence")
    RequestIpl("h4_IslandX_Mansion_Entrance_Fence")
    RequestIpl("h4_north_fence")

    -- Might be needed to ensure the ocean around Cayo Perico is properly rendered
    SetDeepOceanScaler(0.0)

    -- Ensures the minimap (radar) shows the Cayo Perico island area
    SetRadarAsExteriorThisFrame()
    SetRadarAsInteriorThisFrame(`h4_fake_islandx`, 4700.0, -5145.0, 0, 0) 
end)
